package dnsresolver

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestPinnedSourceStrings prevents drift between the Go const values
// and the SQLite CHECK constraint on host_dns_resolvers.source.
func TestPinnedSourceStrings(t *testing.T) {
	pairs := []struct {
		got, want string
	}{
		{string(SourceResolvConf), "resolv-conf"},
		{string(SourceSystemdResolved), "systemd-resolved"},
		{string(SourceNetworkManager), "network-manager"},
		{string(SourceDnsmasq), "dnsmasq"},
		{string(SourceUnbound), "unbound"},
		{string(SourceMacOSScutil), "macos-scutil"},
		{string(SourceWindowsDNSClient), "windows-dnsclient"},
		{string(SourceUnknown), "unknown"},
	}
	for _, p := range pairs {
		if p.got != p.want {
			t.Fatalf("source drift: got %q want %q (breaks SQLite CHECK)",
				p.got, p.want)
		}
	}
}

func TestPinnedScopeStrings(t *testing.T) {
	pairs := []struct {
		got, want string
	}{
		{string(ScopeSystem), "system"},
		{string(ScopeInterface), "interface"},
		{string(ScopeProcess), "process"},
		{string(ScopePerDomain), "per-domain"},
		{string(ScopeUnknown), "unknown"},
	}
	for _, p := range pairs {
		if p.got != p.want {
			t.Fatalf("scope drift: got %q want %q", p.got, p.want)
		}
	}
}

func TestPinnedProtocolStrings(t *testing.T) {
	pairs := []struct {
		got, want string
	}{
		{string(ProtocolUDP), "udp"},
		{string(ProtocolTCP), "tcp"},
		{string(ProtocolDoT), "tls"},
		{string(ProtocolDoH), "https"},
		{string(ProtocolQUIC), "quic"},
		{string(ProtocolUnknown), "unknown"},
	}
	for _, p := range pairs {
		if p.got != p.want {
			t.Fatalf("protocol drift: got %q want %q", p.got, p.want)
		}
	}
}

func TestEncodeStringList(t *testing.T) {
	if EncodeStringList(nil) != "[]" {
		t.Fatal("nil")
	}
	if got := EncodeStringList([]string{"a", "b"}); got != `["a","b"]` {
		t.Fatalf("got %q", got)
	}
}

func TestHashContentsDeterministic(t *testing.T) {
	a := HashContents([]byte("nameserver 1.1.1.1\n"))
	b := HashContents([]byte("nameserver 1.1.1.1\n"))
	if a != b || len(a) != 64 {
		t.Fatalf("a=%q b=%q", a, b)
	}
}

func TestIsPublicResolverIP(t *testing.T) {
	hit := []string{
		"8.8.8.8", "1.1.1.1", "9.9.9.9", "208.67.222.222",
		"2606:4700:4700::1111", "2606:4700:4700::1001",
	}
	for _, s := range hit {
		if !IsPublicResolverIP(s) {
			t.Fatalf("%q must flag public", s)
		}
	}
	miss := []string{"10.0.0.1", "192.168.1.1", "fc00::1", "", "not-an-ip"}
	for _, s := range miss {
		if IsPublicResolverIP(s) {
			t.Fatalf("%q must NOT flag public", s)
		}
	}
}

func TestIsLoopbackResolver(t *testing.T) {
	for _, s := range []string{"127.0.0.1", "127.0.0.53", "::1"} {
		if !IsLoopbackResolver(s) {
			t.Fatalf("%q must flag loopback", s)
		}
	}
	for _, s := range []string{"10.0.0.1", "1.1.1.1", "garbage"} {
		if IsLoopbackResolver(s) {
			t.Fatalf("%q must NOT flag loopback", s)
		}
	}
}

func TestIsDoHOrDoTProtocol(t *testing.T) {
	for _, p := range []Protocol{ProtocolDoH, ProtocolDoT, ProtocolQUIC} {
		if !IsDoHOrDoTProtocol(p) {
			t.Fatalf("%q must flag DoH/DoT/QUIC", p)
		}
	}
	for _, p := range []Protocol{ProtocolUDP, ProtocolTCP, ProtocolUnknown} {
		if IsDoHOrDoTProtocol(p) {
			t.Fatalf("%q must NOT flag", p)
		}
	}
}

func TestAnnotateSecurity(t *testing.T) {
	r := Resolver{Server: "8.8.8.8", Protocol: ProtocolUDP}
	AnnotateSecurity(&r)
	if !r.IsPublicResolver || r.IsLoopback || r.IsDoHOrDoT {
		t.Fatalf("8.8.8.8/udp wrong flags: %+v", r)
	}

	r = Resolver{Server: "127.0.0.53", Protocol: ProtocolUDP}
	AnnotateSecurity(&r)
	if r.IsPublicResolver || !r.IsLoopback || r.IsDoHOrDoT {
		t.Fatalf("127.0.0.53/udp wrong flags: %+v", r)
	}

	r = Resolver{Server: "1.1.1.1", Protocol: ProtocolDoH}
	AnnotateSecurity(&r)
	if !r.IsPublicResolver || r.IsLoopback || !r.IsDoHOrDoT {
		t.Fatalf("1.1.1.1/doh wrong flags: %+v", r)
	}
}

// -- ParseResolvConf -----------------------------------------------------

func TestParseResolvConfTypical(t *testing.T) {
	body := []byte(`# Generated by resolvconf
search corp.local lab.internal
nameserver 10.0.0.53
nameserver 10.0.0.54
options edns0 trust-ad
`)
	got := ParseResolvConf(body, "/etc/resolv.conf")
	if len(got) != 2 {
		t.Fatalf("len=%d, want 2", len(got))
	}
	for _, r := range got {
		if r.Source != SourceResolvConf {
			t.Fatalf("source=%q", r.Source)
		}
		if r.Port != 53 || r.Protocol != ProtocolUDP {
			t.Fatalf("port/proto=%d/%q", r.Port, r.Protocol)
		}
		if !r.IsDNSSEC {
			t.Fatal("edns0+trust-ad must flag dnssec")
		}
		if len(r.SearchDomains) != 2 {
			t.Fatalf("search=%v", r.SearchDomains)
		}
		if r.IsPublicResolver {
			t.Fatalf("10.0.0.53 must NOT flag public: %+v", r)
		}
		if r.FileHash == "" {
			t.Fatal("file_hash missing")
		}
	}
}

func TestParseResolvConfPublicResolverFlagged(t *testing.T) {
	body := []byte("nameserver 8.8.8.8\nnameserver 1.1.1.1\n")
	got := ParseResolvConf(body, "/etc/resolv.conf")
	if len(got) != 2 {
		t.Fatalf("len=%d", len(got))
	}
	for _, r := range got {
		if !r.IsPublicResolver {
			t.Fatalf("%q must flag public", r.Server)
		}
	}
}

func TestParseResolvConfCommentsAndBlanksIgnored(t *testing.T) {
	body := []byte(`# all comments
# more
nameserver 10.0.0.1

# trailing
`)
	got := ParseResolvConf(body, "x")
	if len(got) != 1 || got[0].Server != "10.0.0.1" {
		t.Fatalf("got %+v", got)
	}
}

// -- ParseSystemdResolvedConf -------------------------------------------

func TestParseSystemdResolvedTypical(t *testing.T) {
	body := []byte(`# This file is /etc/systemd/resolved.conf
[Resolve]
DNS=1.1.1.1 1.0.0.1
FallbackDNS=8.8.8.8
Domains=~corp.local lab.internal
DNSSEC=yes
DNSOverTLS=opportunistic
`)
	got := ParseSystemdResolvedConf(body, "/etc/systemd/resolved.conf")
	if len(got) != 3 {
		t.Fatalf("len=%d, want 3: %+v", len(got), got)
	}
	for _, r := range got {
		if r.Source != SourceSystemdResolved {
			t.Fatalf("source=%q", r.Source)
		}
		if !r.IsDNSSEC {
			t.Fatal("DNSSEC=yes must propagate")
		}
		if r.Protocol != ProtocolDoT {
			t.Fatalf("DNSOverTLS=opportunistic → protocol must be DoT; got %q", r.Protocol)
		}
		if r.Port != 853 {
			t.Fatalf("DoT port must be 853; got %d", r.Port)
		}
		if len(r.SearchDomains) != 2 {
			t.Fatalf("domains=%v", r.SearchDomains)
		}
		if !r.IsDoHOrDoT {
			t.Fatal("DoT must flag is_doh_or_dot")
		}
	}
	// Fallback row gets Priority=100.
	var fallback Resolver
	for _, r := range got {
		if r.Server == "8.8.8.8" {
			fallback = r
		}
	}
	if fallback.Priority != 100 {
		t.Fatalf("fallback priority=%d, want 100", fallback.Priority)
	}
}

func TestParseSystemdResolvedNonResolveSectionIgnored(t *testing.T) {
	body := []byte(`[Other]
DNS=1.1.1.1
`)
	got := ParseSystemdResolvedConf(body, "/etc/systemd/resolved.conf")
	if len(got) != 0 {
		t.Fatalf("non-[Resolve] section must be ignored: %+v", got)
	}
}

// -- ParseNetworkManagerKeyfile -----------------------------------------

func TestParseNetworkManagerKeyfileTypical(t *testing.T) {
	body := []byte(`[connection]
id=Corp-Ethernet
interface-name=eth0

[ipv4]
dns=10.0.0.53;10.0.0.54;
dns-search=corp.local;lab.internal;

[ipv6]
dns=fd00::53;
dns-search=corp.local;
`)
	got := ParseNetworkManagerKeyfile(body,
		"/etc/NetworkManager/system-connections/Corp-Ethernet.nmconnection")
	if len(got) != 3 {
		t.Fatalf("len=%d, want 3 (2 v4 + 1 v6): %+v", len(got), got)
	}
	for _, r := range got {
		if r.Source != SourceNetworkManager {
			t.Fatalf("source=%q", r.Source)
		}
		if r.Scope != ScopeInterface {
			t.Fatalf("scope=%q (want interface)", r.Scope)
		}
		if r.InterfaceName != "eth0" {
			t.Fatalf("interface=%q", r.InterfaceName)
		}
		if r.IsPublicResolver {
			t.Fatalf("private IPs must not flag public: %+v", r)
		}
	}
}

func TestParseNetworkManagerKeyfileSemicolonValuesAreNotComments(t *testing.T) {
	// The `;` inside `dns=8.8.8.8;1.1.1.1;` must NOT be stripped as a
	// comment leader. The looksLikeNMValue guard handles this.
	body := []byte(`[ipv4]
dns=8.8.8.8;1.1.1.1;
`)
	got := ParseNetworkManagerKeyfile(body, "x.nmconnection")
	if len(got) != 2 {
		t.Fatalf("dns= list must yield 2 servers, got %d: %+v", len(got), got)
	}
}

// -- ParseDnsmasqConf ---------------------------------------------------

func TestParseDnsmasqConfTypical(t *testing.T) {
	body := []byte(`# /etc/dnsmasq.conf
server=1.1.1.1
server=8.8.8.8#5353
server=/corp.local/10.0.0.53
server=/lab.internal/10.0.0.54#5353
`)
	got := ParseDnsmasqConf(body, "/etc/dnsmasq.conf")
	if len(got) != 4 {
		t.Fatalf("len=%d, want 4: %+v", len(got), got)
	}

	// Per-port parsing.
	var withPort Resolver
	for _, r := range got {
		if r.Server == "8.8.8.8" {
			withPort = r
		}
	}
	if withPort.Port != 5353 {
		t.Fatalf("8.8.8.8 port=%d, want 5353", withPort.Port)
	}

	// Per-domain routing.
	var perDomain Resolver
	for _, r := range got {
		if r.RoutedDomain == "corp.local" {
			perDomain = r
		}
	}
	if perDomain.Scope != ScopePerDomain {
		t.Fatalf("scope=%q for routed entry", perDomain.Scope)
	}
	if perDomain.Server != "10.0.0.53" {
		t.Fatalf("server=%q", perDomain.Server)
	}

	// Combined per-domain + port.
	var combined Resolver
	for _, r := range got {
		if r.RoutedDomain == "lab.internal" {
			combined = r
		}
	}
	if combined.Server != "10.0.0.54" || combined.Port != 5353 {
		t.Fatalf("combined %+v wrong", combined)
	}
}

// -- collector end-to-end -----------------------------------------------

func TestFileCollectorWalksAllSources(t *testing.T) {
	tmp := t.TempDir()
	resolvConf := filepath.Join(tmp, "resolv.conf")
	resolved := filepath.Join(tmp, "resolved.conf")
	resolvedDir := filepath.Join(tmp, "resolved.conf.d")
	nmDir := filepath.Join(tmp, "system-connections")
	dnsmasq := filepath.Join(tmp, "dnsmasq.conf")
	dnsmasqDir := filepath.Join(tmp, "dnsmasq.d")

	must(t, os.MkdirAll(resolvedDir, 0o755))
	must(t, os.MkdirAll(nmDir, 0o755))
	must(t, os.MkdirAll(dnsmasqDir, 0o755))

	mustWrite(t, resolvConf, "nameserver 10.0.0.53\n")
	mustWrite(t, resolved, "[Resolve]\nDNS=1.1.1.1\n")
	mustWrite(t, filepath.Join(resolvedDir, "10-corp.conf"),
		"[Resolve]\nDNS=10.0.0.54\n")
	mustWrite(t, filepath.Join(nmDir, "eth0.nmconnection"),
		"[connection]\ninterface-name=eth0\n[ipv4]\ndns=10.0.0.55;\n")
	mustWrite(t, dnsmasq, "server=10.0.0.56\n")
	mustWrite(t, filepath.Join(dnsmasqDir, "00-extra.conf"),
		"server=/corp.local/10.0.0.57\n")

	c := &fileCollector{
		resolvConf:       resolvConf,
		resolvedConf:     resolved,
		resolvedConfDir:  resolvedDir,
		nmConnectionsDir: nmDir,
		dnsmasqConf:      dnsmasq,
		dnsmasqConfDir:   dnsmasqDir,
		readFile:         os.ReadFile,
		readDir:          os.ReadDir,
	}
	got, err := c.Collect(context.Background())
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	// 1 resolv + 1 systemd main + 1 systemd dropin + 1 NM + 1 dnsmasq + 1 dnsmasq dropin = 6.
	if len(got) != 6 {
		t.Fatalf("want 6 rows, got %d: %+v", len(got), got)
	}

	// Confirm we got the public-resolver flag on 1.1.1.1 from
	// systemd-resolved.conf.
	var publicFound bool
	for _, r := range got {
		if r.IsPublicResolver && r.Server == "1.1.1.1" {
			publicFound = true
		}
	}
	if !publicFound {
		t.Fatal("1.1.1.1 must flag as public resolver")
	}

	// Confirm the per-domain dnsmasq dropin landed correctly.
	var perDomain bool
	for _, r := range got {
		if r.RoutedDomain == "corp.local" {
			perDomain = true
		}
	}
	if !perDomain {
		t.Fatal("per-domain dnsmasq route lost across collector")
	}
}

func TestFileCollectorMissingPathsOK(t *testing.T) {
	c := &fileCollector{
		resolvConf:       "/nope",
		resolvedConf:     "/also-nope",
		resolvedConfDir:  "/nope-dir",
		nmConnectionsDir: "/nope-dir",
		dnsmasqConf:      "/nope",
		dnsmasqConfDir:   "/nope-dir",
		readFile:         os.ReadFile,
		readDir:          os.ReadDir,
	}
	got, err := c.Collect(context.Background())
	if err != nil {
		t.Fatalf("missing must not error: %v", err)
	}
	if len(got) != 0 {
		t.Fatalf("want empty, got %d", len(got))
	}
}

func TestFileCollectorRespectsLexicalOrder(t *testing.T) {
	tmp := t.TempDir()
	resolvedDir := filepath.Join(tmp, "resolved.conf.d")
	must(t, os.MkdirAll(resolvedDir, 0o755))
	mustWrite(t, filepath.Join(resolvedDir, "20-late.conf"),
		"[Resolve]\nDNS=10.0.0.20\n")
	mustWrite(t, filepath.Join(resolvedDir, "10-early.conf"),
		"[Resolve]\nDNS=10.0.0.10\n")

	c := &fileCollector{
		resolvConf:       "/nope",
		resolvedConf:     "/nope",
		resolvedConfDir:  resolvedDir,
		nmConnectionsDir: "/nope",
		dnsmasqConf:      "/nope",
		dnsmasqConfDir:   "/nope",
		readFile:         os.ReadFile,
		readDir:          os.ReadDir,
	}
	got, err := c.Collect(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 2 {
		t.Fatalf("len=%d", len(got))
	}
	// The sort step normalises ordering to (source, server, port) so we
	// can't assert on read order — but both servers must appear.
	servers := []string{got[0].Server, got[1].Server}
	if !contains(servers, "10.0.0.10") || !contains(servers, "10.0.0.20") {
		t.Fatalf("expected both drop-ins read, got %v", servers)
	}
}

func TestSortResolversDeterministic(t *testing.T) {
	in := []Resolver{
		{Source: SourceDnsmasq, Server: "1.1.1.1", Port: 53},
		{Source: SourceResolvConf, Server: "9.9.9.9", Port: 53},
		{Source: SourceResolvConf, Server: "1.1.1.1", Port: 53},
	}
	SortResolvers(in)
	if in[0].Source != SourceDnsmasq {
		t.Fatalf("first=%+v", in[0])
	}
	if in[1].Server != "1.1.1.1" {
		t.Fatalf("mid=%+v", in[1])
	}
}

// -- helpers ------------------------------------------------------------

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatal(err)
	}
}

func mustWrite(t *testing.T, p, body string) {
	t.Helper()
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

func contains(ss []string, want string) bool {
	for _, s := range ss {
		if strings.EqualFold(s, want) {
			return true
		}
	}
	return false
}
