services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otelcol/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/otel-collector.yaml:ro
    ports:
      - "4318:4318"
    networks:
      - kite

networks:
  kite:
    driver: bridge