package driver

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseModinfoBlob_RealishKeys(t *testing.T) {
	t.Parallel()

	blob := []byte("\x00\x00license=GPL\x00description=NVIDIA GPU driver\x00" +
		"version=535.183.06\x00signer=Build time autogenerated kernel key\x00" +
		"sig_hashalgo=sha256\x00depends=drm,drm_kms_helper\x00" +
		"author=Linus Torvalds <torvalds@kernel.org>\x00")

	got := parseModinfoBlob(blob)
	assert.Equal(t, "GPL", got["license"])
	assert.Equal(t, "NVIDIA GPU driver", got["description"])
	assert.Equal(t, "535.183.06", got["version"])
	assert.Equal(t, "Build time autogenerated kernel key", got["signer"])
	assert.Equal(t, "sha256", got["sig_hashalgo"])
	assert.Equal(t, "drm,drm_kms_helper", got["depends"])
	assert.Contains(t, got["author"], "Linus")
}

func TestParseModinfoBlob_DuplicateKeysCommaJoined(t *testing.T) {
	t.Parallel()
	blob := []byte("alias=acpi\x00alias=usb:v1234\x00alias=pci:v5678\x00")
	got := parseModinfoBlob(blob)
	assert.Equal(t, "acpi,usb:v1234,pci:v5678", got["alias"])
}

func TestParseModinfoBlob_EmptyAndMalformedSkipped(t *testing.T) {
	t.Parallel()
	blob := []byte("\x00malformed-no-equals\x00=valuewithoutkey\x00key=val\x00")
	got := parseModinfoBlob(blob)
	assert.Equal(t, map[string]string{"key": "val"}, got)
}

func TestApplyModinfo_PopulatesDriver(t *testing.T) {
	t.Parallel()
	d := LoadedDriver{Name: "nvidia"}
	applyModinfo(&d, map[string]string{
		"version":      "535.183.06",
		"signer":       "NVIDIA Corporation, US",
		"sig_hashalgo": "sha256",
		"depends":      "drm,drm_kms_helper",
	})
	assert.Equal(t, "535.183.06", d.Version)
	assert.Equal(t, "NVIDIA Corporation, US", d.Signer)
	assert.Equal(t, "NVIDIA Corporation", d.Vendor)
	assert.Equal(t, "sha256", d.SignatureAlgo)
	assert.ElementsMatch(t, []string{"drm", "drm_kms_helper"}, d.Dependencies)
}

func TestParseModinfo_MissingFile(t *testing.T) {
	t.Parallel()
	_, err := ParseModinfo(filepath.Join(t.TempDir(), "no-such.ko"))
	require.Error(t, err)
}
