// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/grpc/proto/kite/v1/collector.proto

package kitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AssetType       string                 `protobuf:"bytes,2,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	OsFamily        string                 `protobuf:"bytes,3,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	OsVersion       string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Environment     string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Owner           string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Criticality     string                 `protobuf:"bytes,7,opt,name=criticality,proto3" json:"criticality,omitempty"`
	TagsJson        string                 `protobuf:"bytes,8,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	CollectedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Software        []*InstalledPackage    `protobuf:"bytes,10,rep,name=software,proto3" json:"software,omitempty"`
	DiscoverySource string                 `protobuf:"bytes,11,opt,name=discovery_source,json=discoverySource,proto3" json:"discovery_source,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetSnapshot) Reset() {
	*x = AssetSnapshot{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSnapshot) ProtoMessage() {}

func (x *AssetSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSnapshot.ProtoReflect.Descriptor instead.
func (*AssetSnapshot) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{0}
}

func (x *AssetSnapshot) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AssetSnapshot) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *AssetSnapshot) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *AssetSnapshot) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AssetSnapshot) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AssetSnapshot) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AssetSnapshot) GetCriticality() string {
	if x != nil {
		return x.Criticality
	}
	return ""
}

func (x *AssetSnapshot) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

func (x *AssetSnapshot) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *AssetSnapshot) GetSoftware() []*InstalledPackage {
	if x != nil {
		return x.Software
	}
	return nil
}

func (x *AssetSnapshot) GetDiscoverySource() string {
	if x != nil {
		return x.DiscoverySource
	}
	return ""
}

type InstalledPackage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Vendor         string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Cpe23          string                 `protobuf:"bytes,4,opt,name=cpe23,proto3" json:"cpe23,omitempty"`
	PackageManager string                 `protobuf:"bytes,5,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstalledPackage) Reset() {
	*x = InstalledPackage{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPackage) ProtoMessage() {}

func (x *InstalledPackage) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledPackage.ProtoReflect.Descriptor instead.
func (*InstalledPackage) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{1}
}

func (x *InstalledPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledPackage) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *InstalledPackage) GetCpe23() string {
	if x != nil {
		return x.Cpe23
	}
	return ""
}

func (x *InstalledPackage) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{2}
}

func (x *ReportResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *ReportResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_api_grpc_proto_kite_v1_collector_proto protoreflect.FileDescriptor

const file_api_grpc_proto_kite_v1_collector_proto_rawDesc = "" +
	"\n" +
	"&api/grpc/proto/kite/v1/collector.proto\x12\akite.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x03\n" +
	"\rAssetSnapshot\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\tR\tassetType\x12\x1b\n" +
	"\tos_family\x18\x03 \x01(\tR\bosFamily\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12 \n" +
	"\vcriticality\x18\a \x01(\tR\vcriticality\x12\x1b\n" +
	"\ttags_json\x18\b \x01(\tR\btagsJson\x12=\n" +
	"\fcollected_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x125\n" +
	"\bsoftware\x18\n" +
	" \x03(\v2\x19.kite.v1.InstalledPackageR\bsoftware\x12)\n" +
	"\x10discovery_source\x18\v \x01(\tR\x0fdiscoverySource\"\x97\x01\n" +
	"\x10InstalledPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05cpe23\x18\x04 \x01(\tR\x05cpe23\x12'\n" +
	"\x0fpackage_manager\x18\x05 \x01(\tR\x0epackageManager\"H\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x05R\brejected\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"P\n" +
	"\x11HeartbeatResponse\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime2\x99\x01\n" +
	"\x10CollectorService\x12A\n" +
	"\fReportAssets\x12\x16.kite.v1.AssetSnapshot\x1a\x17.kite.v1.ReportResponse(\x01\x12B\n" +
	"\tHeartbeat\x12\x19.kite.v1.HeartbeatRequest\x1a\x1a.kite.v1.HeartbeatResponseBEZCgithub.com/vulnertrack/kite-collector/api/grpc/proto/kite/v1;kitev1b\x06proto3"

var (
	file_api_grpc_proto_kite_v1_collector_proto_rawDescOnce sync.Once
	file_api_grpc_proto_kite_v1_collector_proto_rawDescData []byte
)

func file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_kite_v1_collector_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_kite_v1_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_proto_kite_v1_collector_proto_rawDesc), len(file_api_grpc_proto_kite_v1_collector_proto_rawDesc)))
	})
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescData
}

var file_api_grpc_proto_kite_v1_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_grpc_proto_kite_v1_collector_proto_goTypes = []any{
	(*AssetSnapshot)(nil),         // 0: kite.v1.AssetSnapshot
	(*InstalledPackage)(nil),      // 1: kite.v1.InstalledPackage
	(*ReportResponse)(nil),        // 2: kite.v1.ReportResponse
	(*HeartbeatRequest)(nil),      // 3: kite.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: kite.v1.HeartbeatResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_api_grpc_proto_kite_v1_collector_proto_depIdxs = []int32{
	5, // 0: kite.v1.AssetSnapshot.collected_at:type_name -> google.protobuf.Timestamp
	1, // 1: kite.v1.AssetSnapshot.software:type_name -> kite.v1.InstalledPackage
	5, // 2: kite.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	0, // 3: kite.v1.CollectorService.ReportAssets:input_type -> kite.v1.AssetSnapshot
	3, // 4: kite.v1.CollectorService.Heartbeat:input_type -> kite.v1.HeartbeatRequest
	2, // 5: kite.v1.CollectorService.ReportAssets:output_type -> kite.v1.ReportResponse
	4, // 6: kite.v1.CollectorService.Heartbeat:output_type -> kite.v1.HeartbeatResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_kite_v1_collector_proto_init() }
func file_api_grpc_proto_kite_v1_collector_proto_init() {
	if File_api_grpc_proto_kite_v1_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_proto_kite_v1_collector_proto_rawDesc), len(file_api_grpc_proto_kite_v1_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_kite_v1_collector_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_kite_v1_collector_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_kite_v1_collector_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_kite_v1_collector_proto = out.File
	file_api_grpc_proto_kite_v1_collector_proto_goTypes = nil
	file_api_grpc_proto_kite_v1_collector_proto_depIdxs = nil
}
