// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/grpc/proto/kite/v1/collector.proto

package kitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetSnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AssetType       string                 `protobuf:"bytes,2,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	OsFamily        string                 `protobuf:"bytes,3,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	OsVersion       string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Environment     string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Owner           string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Criticality     string                 `protobuf:"bytes,7,opt,name=criticality,proto3" json:"criticality,omitempty"`
	TagsJson        string                 `protobuf:"bytes,8,opt,name=tags_json,json=tagsJson,proto3" json:"tags_json,omitempty"`
	CollectedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Software        []*InstalledPackage    `protobuf:"bytes,10,rep,name=software,proto3" json:"software,omitempty"`
	DiscoverySource string                 `protobuf:"bytes,11,opt,name=discovery_source,json=discoverySource,proto3" json:"discovery_source,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetSnapshot) Reset() {
	*x = AssetSnapshot{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSnapshot) ProtoMessage() {}

func (x *AssetSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSnapshot.ProtoReflect.Descriptor instead.
func (*AssetSnapshot) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{0}
}

func (x *AssetSnapshot) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AssetSnapshot) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *AssetSnapshot) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

func (x *AssetSnapshot) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AssetSnapshot) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AssetSnapshot) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AssetSnapshot) GetCriticality() string {
	if x != nil {
		return x.Criticality
	}
	return ""
}

func (x *AssetSnapshot) GetTagsJson() string {
	if x != nil {
		return x.TagsJson
	}
	return ""
}

func (x *AssetSnapshot) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *AssetSnapshot) GetSoftware() []*InstalledPackage {
	if x != nil {
		return x.Software
	}
	return nil
}

func (x *AssetSnapshot) GetDiscoverySource() string {
	if x != nil {
		return x.DiscoverySource
	}
	return ""
}

type ConfigFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingId     string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	RuleId        string                 `protobuf:"bytes,4,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Detail        string                 `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	Remediation   string                 `protobuf:"bytes,8,opt,name=remediation,proto3" json:"remediation,omitempty"`
	FoundAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=found_at,json=foundAt,proto3" json:"found_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigFinding) Reset() {
	*x = ConfigFinding{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFinding) ProtoMessage() {}

func (x *ConfigFinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigFinding.ProtoReflect.Descriptor instead.
func (*ConfigFinding) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigFinding) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *ConfigFinding) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ConfigFinding) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ConfigFinding) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ConfigFinding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ConfigFinding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConfigFinding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ConfigFinding) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *ConfigFinding) GetFoundAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FoundAt
	}
	return nil
}

type InstalledPackage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Vendor         string                 `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Cpe23          string                 `protobuf:"bytes,4,opt,name=cpe23,proto3" json:"cpe23,omitempty"`
	PackageManager string                 `protobuf:"bytes,5,opt,name=package_manager,json=packageManager,proto3" json:"package_manager,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstalledPackage) Reset() {
	*x = InstalledPackage{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledPackage) ProtoMessage() {}

func (x *InstalledPackage) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledPackage.ProtoReflect.Descriptor instead.
func (*InstalledPackage) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{2}
}

func (x *InstalledPackage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstalledPackage) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstalledPackage) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *InstalledPackage) GetCpe23() string {
	if x != nil {
		return x.Cpe23
	}
	return ""
}

func (x *InstalledPackage) GetPackageManager() string {
	if x != nil {
		return x.PackageManager
	}
	return ""
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{3}
}

func (x *ReportResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *ReportResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type EnrollRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PublicKey          string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Hostname           string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MachineFingerprint string                 `protobuf:"bytes,4,opt,name=machine_fingerprint,json=machineFingerprint,proto3" json:"machine_fingerprint,omitempty"`
	EnrollmentToken    string                 `protobuf:"bytes,5,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	AgentVersion       string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	OsFamily           string                 `protobuf:"bytes,7,opt,name=os_family,json=osFamily,proto3" json:"os_family,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{6}
}

func (x *EnrollRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetMachineFingerprint() string {
	if x != nil {
		return x.MachineFingerprint
	}
	return ""
}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetOsFamily() string {
	if x != nil {
		return x.OsFamily
	}
	return ""
}

type EnrollResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Status               string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CaCertificate        []byte                 `protobuf:"bytes,2,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	ClientCertificate    []byte                 `protobuf:"bytes,3,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	ClientKeyEncrypted   []byte                 `protobuf:"bytes,4,opt,name=client_key_encrypted,json=clientKeyEncrypted,proto3" json:"client_key_encrypted,omitempty"`
	CertificateExpiresAt int64                  `protobuf:"varint,5,opt,name=certificate_expires_at,json=certificateExpiresAt,proto3" json:"certificate_expires_at,omitempty"`
	JwksUrl              string                 `protobuf:"bytes,6,opt,name=jwks_url,json=jwksUrl,proto3" json:"jwks_url,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{7}
}

func (x *EnrollResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EnrollResponse) GetCaCertificate() []byte {
	if x != nil {
		return x.CaCertificate
	}
	return nil
}

func (x *EnrollResponse) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

func (x *EnrollResponse) GetClientKeyEncrypted() []byte {
	if x != nil {
		return x.ClientKeyEncrypted
	}
	return nil
}

func (x *EnrollResponse) GetCertificateExpiresAt() int64 {
	if x != nil {
		return x.CertificateExpiresAt
	}
	return 0
}

func (x *EnrollResponse) GetJwksUrl() string {
	if x != nil {
		return x.JwksUrl
	}
	return ""
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Csr           []byte                 `protobuf:"bytes,2,opt,name=csr,proto3" json:"csr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{8}
}

func (x *RenewRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RenewRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RenewResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Status               string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ClientCertificate    []byte                 `protobuf:"bytes,2,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	CertificateExpiresAt int64                  `protobuf:"varint,3,opt,name=certificate_expires_at,json=certificateExpiresAt,proto3" json:"certificate_expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{9}
}

func (x *RenewResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RenewResponse) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

func (x *RenewResponse) GetCertificateExpiresAt() int64 {
	if x != nil {
		return x.CertificateExpiresAt
	}
	return 0
}

// SecureEnvelope wraps JWE-encrypted and JWS-signed payloads for any
// data RPC when end-to-end encryption is enabled.
type SecureEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JweCompact    string                 `protobuf:"bytes,1,opt,name=jwe_compact,json=jweCompact,proto3" json:"jwe_compact,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecureEnvelope) Reset() {
	*x = SecureEnvelope{}
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecureEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecureEnvelope) ProtoMessage() {}

func (x *SecureEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_kite_v1_collector_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecureEnvelope.ProtoReflect.Descriptor instead.
func (*SecureEnvelope) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP(), []int{10}
}

func (x *SecureEnvelope) GetJweCompact() string {
	if x != nil {
		return x.JweCompact
	}
	return ""
}

func (x *SecureEnvelope) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_api_grpc_proto_kite_v1_collector_proto protoreflect.FileDescriptor

const file_api_grpc_proto_kite_v1_collector_proto_rawDesc = "" +
	"\n" +
	"&api/grpc/proto/kite/v1/collector.proto\x12\akite.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x03\n" +
	"\rAssetSnapshot\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\tR\tassetType\x12\x1b\n" +
	"\tos_family\x18\x03 \x01(\tR\bosFamily\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12 \n" +
	"\vcriticality\x18\a \x01(\tR\vcriticality\x12\x1b\n" +
	"\ttags_json\x18\b \x01(\tR\btagsJson\x12=\n" +
	"\fcollected_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x125\n" +
	"\bsoftware\x18\n" +
	" \x03(\v2\x19.kite.v1.InstalledPackageR\bsoftware\x12)\n" +
	"\x10discovery_source\x18\v \x01(\tR\x0fdiscoverySource\"\xa1\x02\n" +
	"\rConfigFinding\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x17\n" +
	"\arule_id\x18\x04 \x01(\tR\x06ruleId\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\a \x01(\tR\x06detail\x12 \n" +
	"\vremediation\x18\b \x01(\tR\vremediation\x125\n" +
	"\bfound_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\afoundAt\"\x97\x01\n" +
	"\x10InstalledPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05cpe23\x18\x04 \x01(\tR\x05cpe23\x12'\n" +
	"\x0fpackage_manager\x18\x05 \x01(\tR\x0epackageManager\"H\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x05R\brejected\"\x91\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"P\n" +
	"\x11HeartbeatResponse\x12;\n" +
	"\vserver_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\x83\x02\n" +
	"\rEnrollRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12/\n" +
	"\x13machine_fingerprint\x18\x04 \x01(\tR\x12machineFingerprint\x12)\n" +
	"\x10enrollment_token\x18\x05 \x01(\tR\x0fenrollmentToken\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12\x1b\n" +
	"\tos_family\x18\a \x01(\tR\bosFamily\"\x81\x02\n" +
	"\x0eEnrollResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0eca_certificate\x18\x02 \x01(\fR\rcaCertificate\x12-\n" +
	"\x12client_certificate\x18\x03 \x01(\fR\x11clientCertificate\x120\n" +
	"\x14client_key_encrypted\x18\x04 \x01(\fR\x12clientKeyEncrypted\x124\n" +
	"\x16certificate_expires_at\x18\x05 \x01(\x03R\x14certificateExpiresAt\x12\x19\n" +
	"\bjwks_url\x18\x06 \x01(\tR\ajwksUrl\";\n" +
	"\fRenewRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x10\n" +
	"\x03csr\x18\x02 \x01(\fR\x03csr\"\x8c\x01\n" +
	"\rRenewResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\x12client_certificate\x18\x02 \x01(\fR\x11clientCertificate\x124\n" +
	"\x16certificate_expires_at\x18\x03 \x01(\x03R\x14certificateExpiresAt\"H\n" +
	"\x0eSecureEnvelope\x12\x1f\n" +
	"\vjwe_compact\x18\x01 \x01(\tR\n" +
	"jweCompact\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId2\xdc\x02\n" +
	"\x10CollectorService\x12A\n" +
	"\fReportAssets\x12\x16.kite.v1.AssetSnapshot\x1a\x17.kite.v1.ReportResponse(\x01\x12C\n" +
	"\x0eReportFindings\x12\x16.kite.v1.ConfigFinding\x1a\x17.kite.v1.ReportResponse(\x01\x12B\n" +
	"\tHeartbeat\x12\x19.kite.v1.HeartbeatRequest\x1a\x1a.kite.v1.HeartbeatResponse\x129\n" +
	"\x06Enroll\x12\x16.kite.v1.EnrollRequest\x1a\x17.kite.v1.EnrollResponse\x12A\n" +
	"\x10RenewCertificate\x12\x15.kite.v1.RenewRequest\x1a\x16.kite.v1.RenewResponseBEZCgithub.com/vulnertrack/kite-collector/api/grpc/proto/kite/v1;kitev1b\x06proto3"

var (
	file_api_grpc_proto_kite_v1_collector_proto_rawDescOnce sync.Once
	file_api_grpc_proto_kite_v1_collector_proto_rawDescData []byte
)

func file_api_grpc_proto_kite_v1_collector_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_kite_v1_collector_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_kite_v1_collector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_proto_kite_v1_collector_proto_rawDesc), len(file_api_grpc_proto_kite_v1_collector_proto_rawDesc)))
	})
	return file_api_grpc_proto_kite_v1_collector_proto_rawDescData
}

var file_api_grpc_proto_kite_v1_collector_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_grpc_proto_kite_v1_collector_proto_goTypes = []any{
	(*AssetSnapshot)(nil),         // 0: kite.v1.AssetSnapshot
	(*ConfigFinding)(nil),         // 1: kite.v1.ConfigFinding
	(*InstalledPackage)(nil),      // 2: kite.v1.InstalledPackage
	(*ReportResponse)(nil),        // 3: kite.v1.ReportResponse
	(*HeartbeatRequest)(nil),      // 4: kite.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 5: kite.v1.HeartbeatResponse
	(*EnrollRequest)(nil),         // 6: kite.v1.EnrollRequest
	(*EnrollResponse)(nil),        // 7: kite.v1.EnrollResponse
	(*RenewRequest)(nil),          // 8: kite.v1.RenewRequest
	(*RenewResponse)(nil),         // 9: kite.v1.RenewResponse
	(*SecureEnvelope)(nil),        // 10: kite.v1.SecureEnvelope
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_api_grpc_proto_kite_v1_collector_proto_depIdxs = []int32{
	11, // 0: kite.v1.AssetSnapshot.collected_at:type_name -> google.protobuf.Timestamp
	2,  // 1: kite.v1.AssetSnapshot.software:type_name -> kite.v1.InstalledPackage
	11, // 2: kite.v1.ConfigFinding.found_at:type_name -> google.protobuf.Timestamp
	11, // 3: kite.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	0,  // 4: kite.v1.CollectorService.ReportAssets:input_type -> kite.v1.AssetSnapshot
	1,  // 5: kite.v1.CollectorService.ReportFindings:input_type -> kite.v1.ConfigFinding
	4,  // 6: kite.v1.CollectorService.Heartbeat:input_type -> kite.v1.HeartbeatRequest
	6,  // 7: kite.v1.CollectorService.Enroll:input_type -> kite.v1.EnrollRequest
	8,  // 8: kite.v1.CollectorService.RenewCertificate:input_type -> kite.v1.RenewRequest
	3,  // 9: kite.v1.CollectorService.ReportAssets:output_type -> kite.v1.ReportResponse
	3,  // 10: kite.v1.CollectorService.ReportFindings:output_type -> kite.v1.ReportResponse
	5,  // 11: kite.v1.CollectorService.Heartbeat:output_type -> kite.v1.HeartbeatResponse
	7,  // 12: kite.v1.CollectorService.Enroll:output_type -> kite.v1.EnrollResponse
	9,  // 13: kite.v1.CollectorService.RenewCertificate:output_type -> kite.v1.RenewResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_kite_v1_collector_proto_init() }
func file_api_grpc_proto_kite_v1_collector_proto_init() {
	if File_api_grpc_proto_kite_v1_collector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_proto_kite_v1_collector_proto_rawDesc), len(file_api_grpc_proto_kite_v1_collector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_kite_v1_collector_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_kite_v1_collector_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_kite_v1_collector_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_kite_v1_collector_proto = out.File
	file_api_grpc_proto_kite_v1_collector_proto_goTypes = nil
	file_api_grpc_proto_kite_v1_collector_proto_depIdxs = nil
}
