// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/grpc/proto/kite/v1/collector.proto

package kitev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollectorService_ReportAssets_FullMethodName     = "/kite.v1.CollectorService/ReportAssets"
	CollectorService_ReportFindings_FullMethodName   = "/kite.v1.CollectorService/ReportFindings"
	CollectorService_Heartbeat_FullMethodName        = "/kite.v1.CollectorService/Heartbeat"
	CollectorService_Enroll_FullMethodName           = "/kite.v1.CollectorService/Enroll"
	CollectorService_RenewCertificate_FullMethodName = "/kite.v1.CollectorService/RenewCertificate"
)

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorServiceClient interface {
	// ReportAssets streams asset snapshots from agents to the server.
	ReportAssets(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AssetSnapshot, ReportResponse], error)
	// ReportFindings streams configuration audit findings from agents.
	ReportFindings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ConfigFinding, ReportResponse], error)
	// Heartbeat allows agents to signal liveness without a full report.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Enroll performs a token-based enrollment handshake to obtain mTLS
	// credentials for an agent connecting to this endpoint.
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// RenewCertificate allows an already-enrolled agent to renew its
	// mTLS client certificate before expiry.
	RenewCertificate(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) ReportAssets(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AssetSnapshot, ReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[0], CollectorService_ReportAssets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AssetSnapshot, ReportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ReportAssetsClient = grpc.ClientStreamingClient[AssetSnapshot, ReportResponse]

func (c *collectorServiceClient) ReportFindings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ConfigFinding, ReportResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[1], CollectorService_ReportFindings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConfigFinding, ReportResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ReportFindingsClient = grpc.ClientStreamingClient[ConfigFinding, ReportResponse]

func (c *collectorServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CollectorService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, CollectorService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorServiceClient) RenewCertificate(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*RenewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewResponse)
	err := c.cc.Invoke(ctx, CollectorService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility.
type CollectorServiceServer interface {
	// ReportAssets streams asset snapshots from agents to the server.
	ReportAssets(grpc.ClientStreamingServer[AssetSnapshot, ReportResponse]) error
	// ReportFindings streams configuration audit findings from agents.
	ReportFindings(grpc.ClientStreamingServer[ConfigFinding, ReportResponse]) error
	// Heartbeat allows agents to signal liveness without a full report.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Enroll performs a token-based enrollment handshake to obtain mTLS
	// credentials for an agent connecting to this endpoint.
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// RenewCertificate allows an already-enrolled agent to renew its
	// mTLS client certificate before expiry.
	RenewCertificate(context.Context, *RenewRequest) (*RenewResponse, error)
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorServiceServer struct{}

func (UnimplementedCollectorServiceServer) ReportAssets(grpc.ClientStreamingServer[AssetSnapshot, ReportResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportAssets not implemented")
}
func (UnimplementedCollectorServiceServer) ReportFindings(grpc.ClientStreamingServer[ConfigFinding, ReportResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportFindings not implemented")
}
func (UnimplementedCollectorServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCollectorServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedCollectorServiceServer) RenewCertificate(context.Context, *RenewRequest) (*RenewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}
func (UnimplementedCollectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	// If the following call panics, it indicates UnimplementedCollectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_ReportAssets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).ReportAssets(&grpc.GenericServerStream[AssetSnapshot, ReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ReportAssetsServer = grpc.ClientStreamingServer[AssetSnapshot, ReportResponse]

func _CollectorService_ReportFindings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).ReportFindings(&grpc.GenericServerStream[ConfigFinding, ReportResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CollectorService_ReportFindingsServer = grpc.ClientStreamingServer[ConfigFinding, ReportResponse]

func _CollectorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServiceServer).RenewCertificate(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kite.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _CollectorService_Heartbeat_Handler,
		},
		{
			MethodName: "Enroll",
			Handler:    _CollectorService_Enroll_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _CollectorService_RenewCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportAssets",
			Handler:       _CollectorService_ReportAssets_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReportFindings",
			Handler:       _CollectorService_ReportFindings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/proto/kite/v1/collector.proto",
}
