package firewall

import (
	"context"
	"errors"
	"testing"
)

func TestPinnedEnumStrings(t *testing.T) {
	pairs := []struct{ got, want string }{
		{string(EngineIPTables), "iptables"},
		{string(EngineNFTables), "nftables"},
		{string(EnginePF), "pf"},
		{string(EngineWindowsFW), "windows-firewall"},
		{string(EngineUFW), "ufw"},
		{string(EngineFirewalld), "firewalld"},
		{string(EngineUnknown), "unknown"},
		{string(DirectionIn), "in"},
		{string(DirectionOut), "out"},
		{string(DirectionForward), "forward"},
		{string(DirectionUnknown), "unknown"},
		{string(ActionAccept), "accept"},
		{string(ActionDrop), "drop"},
		{string(ActionReject), "reject"},
		{string(ActionLog), "log"},
		{string(ActionJump), "jump"},
		{string(ActionReturn), "return"},
		{string(ActionUnknown), "unknown"},
	}
	for _, p := range pairs {
		if p.got != p.want {
			t.Fatalf("enum drift: got %q want %q (breaks SQLite CHECK)",
				p.got, p.want)
		}
	}
}

func TestNormalizeAction(t *testing.T) {
	cases := map[string]Action{
		"ACCEPT":       ActionAccept,
		"accept":       ActionAccept,
		"Allow":        ActionAccept,
		"pass":         ActionAccept,
		"DROP":         ActionDrop,
		"deny":         ActionDrop,
		"Block":        ActionDrop,
		"REJECT":       ActionReject,
		"block return": ActionReject,
		"LOG":          ActionLog,
		"":             ActionUnknown,
		"weird":        ActionUnknown,
	}
	for in, want := range cases {
		if got := NormalizeAction(in); got != want {
			t.Fatalf("NormalizeAction(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestNormalizeDirection(t *testing.T) {
	cases := map[string]Direction{
		"in":      DirectionIn,
		"INPUT":   DirectionIn,
		"out":     DirectionOut,
		"OUTPUT":  DirectionOut,
		"forward": DirectionForward,
		"":        DirectionUnknown,
		"weird":   DirectionUnknown,
	}
	for in, want := range cases {
		if got := NormalizeDirection(in); got != want {
			t.Fatalf("NormalizeDirection(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestIsPermissive(t *testing.T) {
	cases := []struct {
		r    Rule
		want bool
	}{
		{Rule{Action: ActionAccept, SrcCIDR: ""}, true},          // bare ACCEPT = any source
		{Rule{Action: ActionAccept, SrcCIDR: "0.0.0.0/0"}, true}, // explicit any v4
		{Rule{Action: ActionAccept, SrcCIDR: "::/0"}, true},      // any v6
		{Rule{Action: ActionAccept, SrcCIDR: "any"}, true},       // pf shorthand
		{Rule{Action: ActionAccept, SrcCIDR: "10.0.0.0/8"}, false},
		{Rule{Action: ActionDrop, SrcCIDR: "0.0.0.0/0"}, false}, // DROP from any = restrictive
		{Rule{Action: ActionReject, SrcCIDR: ""}, false},
	}
	for i, tc := range cases {
		if got := IsPermissive(tc.r); got != tc.want {
			t.Fatalf("case %d: IsPermissive(%+v) = %v, want %v",
				i, tc.r, got, tc.want)
		}
	}
}

func TestHashRuleIsDeterministicAndIgnoresPriority(t *testing.T) {
	a := Rule{
		Engine: EngineIPTables, Chain: "INPUT", Direction: DirectionIn,
		Action: ActionAccept, Proto: "tcp", DstPort: "22", Priority: 1,
	}
	b := a
	b.Priority = 99 // priority should not affect hash

	ha, hb := HashRule(a), HashRule(b)
	if ha != hb {
		t.Fatalf("HashRule must ignore Priority: %q != %q", ha, hb)
	}
	if len(ha) != 64 {
		t.Fatalf("expected sha256 hex (64 chars), got %d", len(ha))
	}

	c := a
	c.DstPort = "80"
	hc := HashRule(c)
	if hc == ha {
		t.Fatalf("HashRule must change when DstPort changes")
	}
}

func TestParseIPTablesSaveRealisticFixture(t *testing.T) {
	raw := `# Generated by iptables-save v1.8.7 on Mon Jun 23 12:00:00 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 5432 -s 0.0.0.0/0 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -j DROP
-A FORWARD -i eth0 -o eth1 -j ACCEPT
COMMIT
# Completed on Mon Jun 23 12:00:00 2026
`
	rules := parseIPTablesSave(raw)
	if len(rules) != 7 {
		t.Fatalf("want 7 rules, got %d", len(rules))
	}
	// Spot-check the permissive PG rule (rule index 2).
	pg := rules[2]
	if pg.Chain != "INPUT" {
		t.Fatalf("pg chain=%q", pg.Chain)
	}
	if pg.Direction != DirectionIn {
		t.Fatalf("pg direction=%q", pg.Direction)
	}
	if pg.Action != ActionAccept {
		t.Fatalf("pg action=%q", pg.Action)
	}
	if pg.Proto != "tcp" || pg.DstPort != "5432" {
		t.Fatalf("pg proto/port lost: %q/%q", pg.Proto, pg.DstPort)
	}
	if pg.SrcCIDR != "0.0.0.0/0" {
		t.Fatalf("pg src lost: %q", pg.SrcCIDR)
	}
	if !IsPermissive(pg) {
		t.Fatalf("pg should be permissive: %+v", pg)
	}

	// Forward rule has explicit interfaces.
	fwd := rules[6]
	if fwd.Direction != DirectionForward {
		t.Fatalf("forward direction=%q", fwd.Direction)
	}
	if fwd.IfaceIn != "eth0" || fwd.IfaceOut != "eth1" {
		t.Fatalf("forward interfaces lost: in=%q out=%q",
			fwd.IfaceIn, fwd.IfaceOut)
	}

	// Stateful match goes to Extras.
	stateful := rules[4]
	if stateful.Extras == "" {
		t.Fatalf("stateful match should populate Extras")
	}
}

func TestEnsureCIDRAddsHostMaskWhenMissing(t *testing.T) {
	cases := map[string]string{
		"":            "",
		"10.0.0.0/8":  "10.0.0.0/8",
		"192.168.1.1": "192.168.1.1/32",
		"fe80::1":     "fe80::1/128",
		"::1/128":     "::1/128",
	}
	for in, want := range cases {
		if got := ensureCIDR(in); got != want {
			t.Fatalf("ensureCIDR(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestIPTablesCollectorEndToEnd(t *testing.T) {
	c := &iptablesCollector{
		binary:   "iptables-save",
		lookPath: func(string) (string, error) { return "/sbin/iptables-save", nil },
		run: func(_ context.Context, _ string, _ ...string) ([]byte, error) {
			return []byte(`*filter
:INPUT ACCEPT [0:0]
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -j DROP
COMMIT
`), nil
		},
	}
	got, err := c.Collect(context.Background())
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("want 2 rules, got %d", len(got))
	}
	for _, r := range got {
		if r.RuleHash == "" {
			t.Fatalf("rule hash not stamped: %+v", r)
		}
		if r.Engine != EngineIPTables {
			t.Fatalf("engine not stamped: %q", r.Engine)
		}
	}
}

func TestIPTablesCollectorMissingBinary(t *testing.T) {
	c := &iptablesCollector{
		binary:   "iptables-save",
		lookPath: func(string) (string, error) { return "", errors.New("nope") },
		run: func(context.Context, string, ...string) ([]byte, error) {
			t.Fatalf("run must not be invoked when binary missing")
			return nil, nil
		},
	}
	got, err := c.Collect(context.Background())
	if err != nil {
		t.Fatalf("missing binary must not error, got: %v", err)
	}
	if len(got) != 0 {
		t.Fatalf("want empty, got %d", len(got))
	}
}

func TestChainCollectorAggregatesAndSkipsErrors(t *testing.T) {
	good := stubCollector{out: []Rule{
		{Engine: EngineIPTables, Chain: "INPUT", Action: ActionDrop, RuleHash: "h1"},
	}}
	bad := stubCollector{err: errors.New("daemon down")}
	chain := &chainCollector{collectors: []Collector{good, bad, good}}

	got, err := chain.Collect(context.Background())
	if err != nil {
		t.Fatalf("chain Collect: %v", err)
	}
	if len(got) != 2 {
		t.Fatalf("want 2 rules (good × 2), got %d", len(got))
	}
}

func TestChainCollectorRespectsCap(t *testing.T) {
	bulk := stubCollector{out: make([]Rule, MaxRules+10)}
	for i := range bulk.out {
		bulk.out[i] = Rule{Engine: EngineIPTables, RuleHash: itoa(i)}
	}
	chain := &chainCollector{collectors: []Collector{bulk}}
	got, err := chain.Collect(context.Background())
	if err != nil {
		t.Fatalf("Collect: %v", err)
	}
	if len(got) != MaxRules {
		t.Fatalf("want %d (cap), got %d", MaxRules, len(got))
	}
}

// -- helpers --------------------------------------------------------------

type stubCollector struct {
	err error
	out []Rule
}

func (s stubCollector) Name() string { return "stub" }
func (s stubCollector) Collect(_ context.Context) ([]Rule, error) {
	if s.err != nil {
		return nil, s.err
	}
	return s.out, nil
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [11]byte
	i := len(buf)
	neg := n < 0
	if neg {
		n = -n
	}
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
